security:
    providers:
        chain_provider:
            chain:
                providers: [in_memory, entity_provider]

        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$gQznyOZE1dZwA8POTYKBZup5Dy0zWkuM0gyAhU282g6aCGH8TzDG.
                        roles: 'ROLE_ADMIN'

        entity_provider:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        Symfony\Component\Security\Core\User\UserInterface:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_USER:
        ROLE_CAMPAIGN_ADMIN: ROLE_USER
        ROLE_ADMIN: ROLE_CAMPAIGN_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            http_basic:
            provider: chain_provider
            logout: ~

    access_control:
        - { path: "^/admin", roles: ROLE_CAMPAIGN_ADMIN }
        - { path: "^/[a-z]{2}/admin", roles: ROLE_CAMPAIGN_ADMIN }
